export const PATHS = {
	EXIT: '/start',
	BASE: '/*',
	MENU: '/menu',
	BACK: 'back',
	START: '/start',
	START_FLOW: '/start',
	CLOSE: '/close',
}

export const PATHS_LOGIN = {
	LOGIN_FLOW: '/login',
	START_LOGIN: '/login/selectLogin',
	LOGIN: '/login/*',
	SELECT_LOGIN: '/selectLogin',
	READ_FINGER: '/readFinger',
}

export const TEXT = {
	SPANISH: 'Español',
	ENGLISH: 'English',
	DEFAULT_SCREEN: 'Default screen',
	WAIT: 'Espere un momento por favor',
	EMPTY_STRING: '',
	CONFIRM: 'Confirmar',
	CONTINUE: 'Continuar',
	COMEBACK: 'Volver',
	ESC: 'Salir',
	SELECT_ACCOUNT_TITLE: 'Seleccione la cuenta',
	WELCOME: 'Bienvenida',
	MAIN_MENU: 'Menu principal',
	DO_YOU_NEED_TIME: '¿Necesitas más tiempo?',
	TOUCH: 'Toque la pantalla para comenzar',
	NO_OPTION_TIMEOUT: 'No',
	OK_OPTION_TIMEOUT: 'Sí',
	TITLE_INPUT: 'Ingresar Monto a Extraer',
	DISPENSE_OPTION: 'Extraer',
	DEPOSIT_OPTION: 'Depositar',
	ASK: 'Consultas',
	ACCOUNTS: 'Cuentas',
	BALANCE_OPTIONS: 'Saldos',
	KEYS: 'Claves',
	CHIP_1: '100,000',
	CHIP_2: '10,000',
	CHIP_3: '1,000',
	LOGIN_OPTION_1: 'Dni',
	LOGIN_OPTION_2: 'Biométrico',
	LOGIN_OPTION_3: 'Tarjeta',
	LOGIN_OPTION_4: 'Sin iniciar sesion',
	TITLE_LOGIN: 'Iniciar Sesión',
	AVAILABLE: 'Disponible',
	BALANCE: 'Saldo',
	TIME_LEFT: 'Tiempo restante',
	NUMBER_MULTIPLE: 'Monto debe ser múltiplo de 100',
	NUMBER_REQUERIMENT: 'Debe ingresar un valor',
	NUMBER_MIN: 'Monto menor al mínimo aceptado',
	NUMBER_UP: 'Monto mayor al disponible en esta terminal',
	NUMBER_DOWN: 'Monto mayor al saldo disponible',
	TITLE_AMOUNT_ADVICE: 'No es posible entregar el monto que indicaste',
	SUBTITLE_SUGGEST: 'Te sugerimos $',
	READ_FINGER: 'Lectura de huella',
	VALIDATING: 'Validando huella',
	CONFIRM_USER: '¿Es usted',
	ERROR_LOGIN: 'Disculpe hubo un error',
	FAIL_LOGIN: 'Intente nuevamente',
	OK: 'Ok',
	NO: 'No soy yo',
	CANCEL: 'Cancelar',
	PREPARING: 'Aguarde un momento',
	PRESENT: 'Retire el dinero por favor.',
	RETRACT: 'Cancelando Dispensado.',
	TAKEN: 'Aguarde mientras finaliza.',
	ERROR_DISPENSE: 'Disculpe, hubo un error.',
	END_ERROR: 'Ha fallado en la finalización',
	END_OK: '¿Desea realizar otra operación?',
	EXTRACT_AGAIN: 'Otra Extracción',
	PRINT: 'Imprimir ticket',
	ERROR_SELECT: 'Disculpe hubo un error al acceder',
	STOP_TIMEOUT: 'Detener Timeout',
	RESTART_TIMEOUT: 'Reiniciar Timeout',
}

export const LENGUAGE_OPTIONS = {
	[TEXT.SPANISH]: () => TEXT_SPA,
	[TEXT.ENGLISH]: () => TEXT_ENG,
}

export const TEXT_SPA = {
	[TEXT.SPANISH]: 'Español',
	[TEXT.ENGLISH]: 'English',
	[TEXT.DEFAULT_SCREEN]: 'Default screen',
	[TEXT.WAIT]: 'Espere un momento por favor',
	[TEXT.EMPTY_STRING]: '',
	[TEXT.CONFIRM]: 'Confirmar',
	[TEXT.CONTINUE]: 'Continuar',
	[TEXT.COMEBACK]: 'Volver',
	[TEXT.ESC]: 'Salir',
	[TEXT.SELECT_ACCOUNT_TITLE]: 'Seleccione la cuenta',
	[TEXT.WELCOME]: 'Bienvenida',
	[TEXT.MAIN_MENU]: 'Menu principal',
	[TEXT.DO_YOU_NEED_TIME]: '¿Necesitas más tiempo?',
	[TEXT.TOUCH]: 'Toque la pantalla para comenzar',
	[TEXT.NO_OPTION_TIMEOUT]: 'No',
	[TEXT.OK_OPTION_TIMEOUT]: 'Sí',
	[TEXT.TITLE_INPUT]: 'Ingresar Monto a Extraer',
	[TEXT.DISPENSE_OPTION]: 'Extraer',
	[TEXT.DEPOSIT_OPTION]: 'Depositar',
	[TEXT.ASK]: 'Consultas',
	[TEXT.ACCOUNTS]: 'Cuentas',
	[TEXT.BALANCE_OPTIONS]: 'Saldos',
	[TEXT.KEYS]: 'Claves',
	[TEXT.CHIP_1]: '100,000',
	[TEXT.CHIP_2]: '10,000',
	[TEXT.CHIP_3]: '1,000',
	[TEXT.LOGIN_OPTION_1]: 'Ingrese con Dni.',
	[TEXT.LOGIN_OPTION_2]: 'Ingrese con Biométrico.',
	[TEXT.LOGIN_OPTION_3]: 'Ingrese con Tarjeta.',
	[TEXT.LOGIN_OPTION_4]: 'Sin iniciar sesion.',
	[TEXT.TITLE_LOGIN]: 'Iniciar Sesión',
	[TEXT.AVAILABLE]: 'Disponible',
	[TEXT.BALANCE]: 'Saldo',
	[TEXT.TIME_LEFT]: 'Tiempo restante',
	[TEXT.NUMBER_MULTIPLE]: 'Monto debe ser múltiplo de 100',
	[TEXT.NUMBER_REQUERIMENT]: 'Debe ingresar un valor',
	[TEXT.NUMBER_MIN]: 'Monto menor al mínimo aceptado',
	[TEXT.NUMBER_UP]: 'Monto mayor al disponible en esta terminal',
	[TEXT.NUMBER_DOWN]: 'Monto mayor al saldo disponible',
	[TEXT.TITLE_AMOUNT_ADVICE]: 'No es posible entregar el monto que indicaste',
	[TEXT.SUBTITLE_SUGGEST]: 'Te sugerimos $',
	[TEXT.READ_FINGER]: 'Lectura de huella',
	[TEXT.VALIDATING]: 'Validando huella',
	[TEXT.CONFIRM_USER]: '¿Es usted',
	[TEXT.ERROR_LOGIN]: 'Disculpe hubo un error',
	[TEXT.FAIL_LOGIN]: 'Intente nuevamente',
	[TEXT.OK]: 'Ok',
	[TEXT.NO]: 'No soy yo',
	[TEXT.CANCEL]: 'Cancelar',
	[TEXT.PREPARING]: 'Aguarde un momento',
	[TEXT.PRESENT]: 'Retire el dinero por favor.',
	[TEXT.RETRACT]: 'Cancelando Dispensado.',
	[TEXT.TAKEN]: 'Aguarde mientras finaliza.',
	[TEXT.ERROR_DISPENSE]: 'Disculpe, hubo un error.',
	[TEXT.END_ERROR]: 'Ha fallado en la finalización',
	[TEXT.END_OK]: '¿Desea realizar otra operación?',
	[TEXT.EXTRACT_AGAIN]: 'Otra Extracción',
	[TEXT.PRINT]: 'Imprimir ticket',
	[TEXT.ERROR_SELECT]: 'Disculpe hubo un error al acceder',
	[TEXT.STOP_TIMEOUT]: 'Detener Timeout',
	[TEXT.RESTART_TIMEOUT]: 'Reiniciar Timeout',
}

export const TEXT_ENG = {
	[TEXT.SPANISH]: 'Español',
	[TEXT.ENGLISH]: 'English',
	[TEXT.DEFAULT_SCREEN]: 'Default screen',
	[TEXT.WAIT]: 'Wait a moment please.',
	[TEXT.EMPTY_STRING]: '',
	[TEXT.CONFIRM]: 'Confirm',
	[TEXT.CONTINUE]: 'Continue',
	[TEXT.COMEBACK]: 'Back',
	[TEXT.ESC]: 'Exit',
	[TEXT.SELECT_ACCOUNT_TITLE]: 'Select the account',
	[TEXT.WELCOME]: 'Welcome',
	[TEXT.MAIN_MENU]: 'Main menu',
	[TEXT.DO_YOU_NEED_TIME]: 'Do you need more time?',
	[TEXT.TOUCH]: 'Touch the screen to begin',
	[TEXT.NO_OPTION_TIMEOUT]: 'No',
	[TEXT.OK_OPTION_TIMEOUT]: 'Yes',
	[TEXT.TITLE_INPUT]: 'Input amount to withdraw',
	[TEXT.DISPENSE_OPTION]: 'Dispense',
	[TEXT.DEPOSIT_OPTION]: 'Deposit',
	[TEXT.ASK]: 'Ask',
	[TEXT.ACCOUNTS]: 'Accounts',
	[TEXT.BALANCE_OPTIONS]: 'Balances',
	[TEXT.KEYS]: 'Keys',
	[TEXT.CHIP_1]: '100,000',
	[TEXT.CHIP_2]: '10,000',
	[TEXT.CHIP_3]: '1,000',
	[TEXT.LOGIN_OPTION_1]: 'Login with Dni.',
	[TEXT.LOGIN_OPTION_2]: 'Login with Finger',
	[TEXT.LOGIN_OPTION_3]: 'Login with card.',
	[TEXT.LOGIN_OPTION_4]: 'Start without login.',
	[TEXT.TITLE_LOGIN]: 'Login',
	[TEXT.AVAILABLE]: 'Available',
	[TEXT.BALANCE]: 'Balance',
	[TEXT.TIME_LEFT]: 'Time left',
	[TEXT.NUMBER_MULTIPLE]: 'The Amount  must be 100 multiple',
	[TEXT.NUMBER_REQUERIMENT]: 'You should input a value',
	[TEXT.NUMBER_MIN]: 'Amount less than min accepted',
	[TEXT.NUMBER_UP]: 'Amount bigger than available on this atm',
	[TEXT.NUMBER_DOWN]: 'Amount bigger than balance available',
	[TEXT.TITLE_AMOUNT_ADVICE]: "It's not possible withdraw the input amount",
	[TEXT.SUBTITLE_SUGGEST]: 'We suggest you $',
	[TEXT.READ_FINGER]: 'Read finger',
	[TEXT.VALIDATING]: 'Checking finger',
	[TEXT.CONFIRM_USER]: 'Are you',
	[TEXT.ERROR_LOGIN]: "I'm sorry , it was a error.",
	[TEXT.FAIL_LOGIN]: 'Try again',
	[TEXT.OK]: 'Ok',
	[TEXT.NO]: "I'm not",
	[TEXT.CANCEL]: 'Cancel',
	[TEXT.PREPARING]: 'Take a moment',
	[TEXT.PRESENT]: 'Withdraw the bills, please.',
	[TEXT.RETRACT]: 'Canceling Dispense.',
	[TEXT.TAKEN]: "Wait while it's finished.",
	[TEXT.ERROR_DISPENSE]: 'Sorry,  error happen.',
	[TEXT.END_ERROR]: 'Problem to finish last step',
	[TEXT.END_OK]: 'Do you want to do any other operation?',
	[TEXT.EXTRACT_AGAIN]: 'Dispense Again',
	[TEXT.PRINT]: 'Print ticket',
	[TEXT.ERROR_SELECT]: "I'm sorry , it was a error to access",
	[TEXT.STOP_TIMEOUT]: 'Stop timeout',
	[TEXT.RESTART_TIMEOUT]: 'Restart Timeout',
}

/*IMAGES-----------------------------------------------------------------------*/

export const IMAGES = {
	IMG_CIM: 'cim',
	IMG_CDM: 'cdm',
	BACKGROUND_1: 'background1',
	BACKGROUND_2: 'background2',
}

export const BACKGROUND_1 = {
	img: IMAGES.BACKGROUND_1,
	width: '50%',
	borderRadius: '0px 0% 0% 0px',
	left: '0%',
	colour: 'carrusel1',
}

export const BACKGROUND_2 = {
	img: IMAGES.BACKGROUND_2,
	width: '70%',
	borderRadius: '0px 0% 0% 0px',
	left: '50%',
	colour: 'carrusel2',
}

export const STYLES = {
	default: 'radial-gradient(circle, rgba(245, 245, 245, 1) 0%, rgba(255, 255, 255, 1) 80%, rgba(190, 191, 191, 1) 100%)',
}
